# Generated by Django 5.1.6 on 2025-02-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_from", models.CharField(max_length=50)),
                ("_to", models.CharField(max_length=50)),
            ],
        ),
    ]
