# Generated by Django 5.1.6 on 2025-02-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="_from",
            new_name="destination",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="_to",
            new_name="start",
        ),
    ]
