# Generated by Django 5.1.6 on 2025-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="founder",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="about",
            name="mission",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="about",
            name="profile",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="about",
            name="vision",
            field=models.TextField(blank=True),
        ),
    ]
