# Generated by Django 5.1.6 on 2025-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_headoffice"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallcenterMob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mob", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="CallcenterTel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tel", models.CharField(max_length=15)),
            ],
        ),
    ]
