# Generated by Django 5.1.6 on 2025-02-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_callcentermob_callcentertel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Query",
        ),
    ]
