# Generated by Django 5.1.6 on 2025-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_contact_query"),
    ]

    operations = [
        migrations.CreateModel(
            name="section2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=200)),
                ("link", models.CharField(max_length=20)),
            ],
        ),
    ]
