# Generated by Django 5.1.6 on 2025-02-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusDetails",
            fields=[
                ("bus_id", models.AutoField(primary_key=True, serialize=False)),
                ("bus_name", models.CharField(max_length=20)),
                ("bus_type", models.CharField(max_length=50)),
                ("bus_details", models.CharField(max_length=100)),
                ("sit_capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TravelDetails",
            fields=[
                ("travel_id", models.AutoField(primary_key=True, serialize=False)),
                ("leaving_from", models.CharField(max_length=50)),
                ("going_to", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("day", models.CharField(editable=False, max_length=20)),
                ("fare", models.IntegerField()),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.busdetails"
                    ),
                ),
            ],
        ),
    ]
