# Generated by Django 5.1.6 on 2025-02-26 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_busdetails_traveldetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=5)),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.traveldetails",
                    ),
                ),
            ],
        ),
    ]
