# Generated by Django 5.1.6 on 2025-02-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_seat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Seat",
        ),
    ]
