# Generated by Django 5.1.6 on 2025-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_delete_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveldetails",
            name="booked_seat",
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
    ]
