# Generated by Django 5.1.6 on 2025-02-26 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_traveldetails_booked_seat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_name", models.CharField(max_length=100)),
                ("passenger_email", models.EmailField(max_length=254)),
                ("number_of_ticket", models.IntegerField()),
                ("transaction_id", models.CharField(max_length=50)),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.traveldetails",
                    ),
                ),
            ],
        ),
    ]
