# Generated by Django 5.1.6 on 2025-02-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_passenger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="travel",
        ),
        migrations.DeleteModel(
            name="TravelDetails",
        ),
    ]
